#pragma config(Sensor, dgtl1,  rightencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftencoder,    sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

wait1Msec (2000);

SensorValue[rightEncoder] = 0;
SensorValue[leftEncoder] = 0;
//First Forward Movement
while(SensorValue[leftEncoder] > 1000)
	{
		if(sensorvalue[leftEncoder] > SensorValue[rightEncoder])
			{
				motor[port2] = 70;
				motor[port3] = -50;
			}
		if(sensorvalue[leftEncoder] < SensorValue[rightEncoder])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		if(sensorvalue[leftEncoder] = SensorValue[rightEncoder])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		}
}
