#pragma config(Sensor, dgtl1,  rightencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(1000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[rightEncoder] < 800)
	{
		motor[port2] = 93;
		motor[port3] = -83;
	}
	motor[port2] = 0;
	motor[port3] = 0;

	wait1Msec(1000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;



	while(SensorValue[rightEncoder] > -800)
	{
		motor[port2] = -93;
		motor[port3] = 93;
	}
	motor[port2] = 0;
	motor[port3] = 0;

	wait1Msec(1000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[rightEncoder] < 1900)
	{
		motor[port2] = 93;
		motor[port3] = -83;
	}
	motor[port2] = 0;
	motor[port3] = 0;

	wait1Msec(1000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;



	while(SensorValue[rightEncoder] > -1900)
	{
		motor[port2] = -93;
		motor[port3] = 93;
	}
	motor[port2] = 0;
	motor[port3] = 0;

	wait1Msec(1000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[rightEncoder] < 2800)
	{
		motor[port2] = 93;
		motor[port3] = -83;
	}
	motor[port2] = 0;
	motor[port3] = 0;

	wait1Msec(1000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;



	while(SensorValue[rightEncoder] > -2800)
	{
		motor[port2] = -63;
		motor[port3] = 66;
	}
	motor[port2] = 0;
	motor[port3] = 0;

	wait1Msec(1000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[rightEncoder] < 3800)
	{
		motor[port2] = 63;
		motor[port3] = -53;
	}
	motor[port2] = 0;
	motor[port3] = 0;

	wait1Msec(1000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;



	while(SensorValue[rightEncoder] > -3800)
	{
		motor[port2] = -63;
		motor[port3] = 66;
	}
	motor[port2] = 0;
	motor[port3] = 0;
}
