#pragma config(Sensor, dgtl1,  Right,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Left,           sensorQuadEncoder)
//13" robot width, Tire radius 1.5"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
/*
{

wait1Msec (200);

SensorValue[Right] = 0;
SensorValue[Left] = 0;
//First Forward Movement
while(SensorValue[Left] < 1050)
	{
		if(sensorvalue[Left] > SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -50;
			}
		if(sensorvalue[Left] < SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		if(sensorvalue[Left] == SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		}

sensorValue[Right] = 0;
while(sensorValue[Right] < 950)

{
	motor[port2] = 127;
	motor[port3] = 0;
}
motor[port2] = 0;

wait1Msec (200);

SensorValue[Right] = 0;
SensorValue[Left] = 0;
//Second Forward Movement
while(SensorValue[Left] < 600)
	{
		if(sensorvalue[Left] > SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -50;
			}
		if(sensorvalue[Left] < SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		if(sensorvalue[Left] == SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		}

sensorValue[Right] = 0;
while(sensorValue[Right] < 950)

{
	motor[port2] = 127;
	motor[port3] = 0;
}
motor[port2] = 0;

SensorValue[Right] = 0;
SensorValue[Left] = 0;
//Third Forward Movement
while(SensorValue[Left] < 800)
	{
		if(sensorvalue[Left] > SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -50;
			}
		if(sensorvalue[Left] < SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		if(sensorvalue[Left] == SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		}

sensorValue[Right] = 0;
while(sensorValue[Right] < 550)

{
	motor[port2] = 60;
	motor[port3] = 60;
}

motor[port2] = 0;
motor[port3] = 0;

SensorValue[Right] = 0;
SensorValue[Left] = 0;
//Fourth Forward Movement
while(SensorValue[Left] < 950)
	{
		if(sensorvalue[Left] > SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -50;
			}
		if(sensorvalue[Left] < SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		if(sensorvalue[Left] == SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
					}
		}
					sensorValue[Right] = 0;


while(sensorValue[Right] < 550)

{
	motor[port2] = 60;
	motor[port3] = 60;
}
}
*/
{

wait1Msec (200);

SensorValue[Right] = 0;
SensorValue[Left] = 0;
//First Forward Movement
while(SensorValue[Left] < 1200)
	{
		if(sensorvalue[Left] > SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -50;
			}
		if(sensorvalue[Left] < SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		if(sensorvalue[Left] == SensorValue[Right])
			{
				motor[port2] = 70;
				motor[port3] = -63;
			}
		}

		wait1Msec (200);
	}


SensorValue[Right] = 0;
SensorValue[Left] = 0;
//First Forward Movement
while(SensorValue[Left] < -1050)
	{
		if(sensorvalue[Left] > SensorValue[Right])
			{
				motor[port2] = -70;
				motor[port3] = 50;
			}
		if(sensorvalue[Left] < SensorValue[Right])
			{
				motor[port2] = -70;
				motor[port3] = 63;
			}
		if(sensorvalue[Left] == SensorValue[Right])
			{
				motor[port2] = -70;
				motor[port3] = 63;
			}
	}
}
